services:
  laravel.test:
    build:
      context: .
      target: frankenphp_prod
    environment:
      SERVER_NAME: ${SERVER_NAME}
      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      DB_DATABASE: ${DB_DATABASE}
      DB_CONNECTION: "${DB_CONNECTION:-sqlite}"
      LOG_STACK: "${LOG_STACK:-stderr}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - storage:/app/storage

volumes:
  caddy_data:
  caddy_config:
  storage: