name: tests

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup app
        run: |
          cp .env.example .env
          touch database/database.sqlite
          php artisan key:generate
          php artisan migrate

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Test backend
        run: composer test

      - name: Run PHP Server
        run: php -S localhost:8000 -t public > storage/logs/server.log 2>&1 &

      - name: Wait for Server to Start
        run: sleep 2

      - name: Make check_reachability.sh executable
        run: chmod +x .github/scripts/check_reachability.sh

      - name: Check API reachability
        run: .github/scripts/check_reachability.sh http://localhost:8000/api

      - name: Check Docs reachability
        run: .github/scripts/check_reachability.sh http://localhost:8000/docs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test frontend
        run: LARAVEL_BYPASS_ENV_CHECK=1 npm run test -- run

      - name: Check App reachability
        run: .github/scripts/check_reachability.sh http://localhost:8000

      - name: Show Laravel logs
        if: failure()
        run: cat storage/logs/laravel.log

      - name: Show server logs
        if: failure()
        run: cat storage/logs/server.log